<?php

use Illuminate\Database\Seeder;

class FunctionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('functions')->insert([
            [
                'post_id' => '1',
                'name' => 'ログイン',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '1',
                'name' => 'ログアウト',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '1',
                'name' => 'ユーザー登録',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '1',
                'name' => '投稿',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '1',
                'name' => '投稿表示',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '1',
                'name' => '投稿編集',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '1',
                'name' => '投稿削除',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '1',
                'name' => 'いいね',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '1',
                'name' => 'いいね削除',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '1',
                'name' => 'ユーザー情報登録',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '1',
                'name' => 'ユーザー情報変更',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '1',
                'name' => 'フォロー',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '1',
                'name' => 'フォロー解除',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '1',
                'name' => 'ブロック',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '1',
                'name' => 'ブロック解除',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '1',
                'name' => 'フォローリスト表示',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '1',
                'name' => 'フォロワーリスト表示',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '1',
                'name' => 'ユーザー検索',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '1',
                'name' => 'お知らせ表示',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '1',
                'name' => 'よくある質問',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '1',
                'name' => '【管理者】ログイン',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '1',
                'name' => '【管理者】ログアウト',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '1',
                'name' => '【管理者】お知らせ登録',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '1',
                'name' => '【管理者】お知らせ表示',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '1',
                'name' => '【管理者】よくある質問登録',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '1',
                'name' => '【管理者】よくある質問表示',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '2',
                'name' => 'ログイン',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '2',
                'name' => 'ログアウト',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '2',
                'name' => 'ユーザー登録',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '2',
                'name' => '商品検索',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '2',
                'name' => '商品表示(一覧)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '2',
                'name' => '商品表示(ランキング)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '2',
                'name' => '商品表示(コーディネート)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '2',
                'name' => '商品表示(シーン別)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '2',
                'name' => '商品表示(新商品別)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '2',
                'name' => '商品表示(性別別)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '2',
                'name' => 'カテゴリー一覧',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '2',
                'name' => 'instagramへの遷移',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '2',
                'name' => 'facebookへの遷移',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '2',
                'name' => 'twitterへの遷移',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '2',
                'name' => 'LINEへの遷移',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '2',
                'name' => '運営からのお知らせ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '2',
                'name' => 'お気に入り表示',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '2',
                'name' => 'お気に入り登録',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '2',
                'name' => 'お気に入り解除',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '2',
                'name' => 'カートに入れる',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '2',
                'name' => 'カートから外す',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '2',
                'name' => 'カートの中を表示',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '2',
                'name' => 'レビュー投稿',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '2',
                'name' => 'レビュー削除',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '2',
                'name' => 'レビュー表示',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '2',
                'name' => 'ユーザー情報変更',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '2',
                'name' => 'ユーザー情報表示',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '2',
                'name' => '購入',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '2',
                'name' => '購入履歴表示',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '2',
                'name' => '再度購入',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '3',
                'name' => 'ログイン',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '3',
                'name' => 'ログアウト',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '3',
                'name' => 'ユーザー登録',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '3',
                'name' => 'ユーザー検索',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '3',
                'name' => 'お問い合わせ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '3',
                'name' => 'facebookへの遷移',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '3',
                'name' => 'instagramへの遷移',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '3',
                'name' => 'twitterへの遷移',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '3',
                'name' => '投稿表示(行ったことのある地域別)（国内）',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '3',
                'name' => '投稿表示(行ったことのある地域別)（海外）',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '3',
                'name' => '投稿表示(カテゴリー別)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '3',
                'name' => '投稿した写真をトップ画面にランダム表示',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '3',
                'name' => 'ユーザー情報表示',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '3',
                'name' => '行ったことのある都道府県表示',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '3',
                'name' => 'メモ登録',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '3',
                'name' => 'メモ表示',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '3',
                'name' => 'お問い合わせ表示',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '3',
                'name' => '投稿',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '3',
                'name' => '投稿編集',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '3',
                'name' => '投稿削除',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '3',
                'name' => 'ユーザー情報編集',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '4',
                'name' => 'LINE API',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '4',
                'name' => 'instagram API',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '4',
                'name' => 'ループする流れる写真（jQuery）',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '4',
                'name' => 'カレンダー表示',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '4',
                'name' => '開店日をカレンダーに表示（jQuery）',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '4',
                'name' => '設定した開店日の表示',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '4',
                'name' => 'あいまい検索',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '4',
                'name' => 'レスポンシブ対応',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '4',
                'name' => '【管理者】マルチログイン機能',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '4',
                'name' => '【管理者】カレンダー表示',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '4',
                'name' => '【管理者】開店日をカレンダーに表示（jQuery）',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '4',
                'name' => '【管理者】開店日設定、編集、削除',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '4',
                'name' => '【管理者】予約待ち人数表示',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '4',
                'name' => '【管理者】予約待ちユーザー表示',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '4',
                'name' => '【管理者】CRUD機能',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '4',
                'name' => '【管理者】ドラックアンドドロップ（jQuery）',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '4',
                'name' => '【管理者】公式LINE連携（公式LINEで予約、予約キャンセル可能。）',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '4',
                'name' => '【管理者】予約時、キャンセル時公式LINEにメッセージ送信',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '4',
                'name' => '【管理者】リーダーへの意見投稿',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '4',
                'name' => '【リーダー】パスワード変更',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'post_id' => '4',
                'name' => '【リーダー】管理者からの意見表示',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
